// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAemp8-I5gMcmM2jp3ylwfag_JPUdTE_z4',
    appId: '1:613993761425:web:9df1d25e8c10a088a6cd30',
    messagingSenderId: '613993761425',
    projectId: 'fresh-fade-booking',
    authDomain: 'fresh-fade-booking.firebaseapp.com',
    storageBucket: 'fresh-fade-booking.firebasestorage.app',
    measurementId: 'G-6GF68QMBC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOLGTzX1nx1RNYJfFTqRqCCoLQIJeLSbw',
    appId: '1:613993761425:android:753085bd27886c87a6cd30',
    messagingSenderId: '613993761425',
    projectId: 'fresh-fade-booking',
    storageBucket: 'fresh-fade-booking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRBQW7DVWrHatJfLGcB6wP1HP9Y4w6otM',
    appId: '1:613993761425:ios:b1971dcc43d280eda6cd30',
    messagingSenderId: '613993761425',
    projectId: 'fresh-fade-booking',
    storageBucket: 'fresh-fade-booking.firebasestorage.app',
    iosClientId: '613993761425-1mhhu5t692lkvnp006rkrq36e55cmmve.apps.googleusercontent.com',
    iosBundleId: 'com.freshfade.barberpannel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRBQW7DVWrHatJfLGcB6wP1HP9Y4w6otM',
    appId: '1:613993761425:ios:b1971dcc43d280eda6cd30',
    messagingSenderId: '613993761425',
    projectId: 'fresh-fade-booking',
    storageBucket: 'fresh-fade-booking.firebasestorage.app',
    iosClientId: '613993761425-1mhhu5t692lkvnp006rkrq36e55cmmve.apps.googleusercontent.com',
    iosBundleId: 'com.freshfade.barberpannel',
  );
}
